{ lib, config, pkgs, ... }:
let
  uutils = [
    "uutils-arch"
    "uutils-base32"
    "uutils-base64"
    "uutils-basename"
    "uutils-basenc"
    "uutils-cat"
    "uutils-chgrp"
    "uutils-chmod"
    "uutils-chown"
    "uutils-chroot"
    "uutils-cksum"
    "uutils-comm"
    "uutils-coreutils"
    "uutils-cp"
    "uutils-csplit"
    "uutils-cut"
    "uutils-date"
    "uutils-dd"
    "uutils-df"
    "uutils-dir"
    "uutils-dircolors"
    "uutils-dirname"
    "uutils-du"
    "uutils-echo"
    "uutils-env"
    "uutils-expand"
    "uutils-expr"
    "uutils-factor"
    "uutils-false"
    "uutils-fmt"
    "uutils-fold"
    "uutils-groups"
    "uutils-hashsum"
    "uutils-head"
    "uutils-hostid"
    "uutils-hostname"
    "uutils-id"
    "uutils-install"
    "uutils-join"
    "uutils-kill"
    "uutils-link"
    "uutils-ln"
    "uutils-logname"
    "uutils-ls"
    "uutils-mkdir"
    "uutils-mkfifo"
    "uutils-mknod"
    "uutils-mktemp"
    "uutils-more"
    "uutils-mv"
    "uutils-nice"
    "uutils-nl"
    "uutils-nohup"
    "uutils-nproc"
    "uutils-numfmt"
    "uutils-od"
    "uutils-paste"
    "uutils-pathchk"
    "uutils-pinky"
    "uutils-pr"
    "uutils-printenv"
    "uutils-printf"
    "uutils-ptx"
    "uutils-pwd"
    "uutils-readlink"
    "uutils-realpath"
    "uutils-rm"
    "uutils-rmdir"
    "uutils-seq"
    "uutils-shred"
    "uutils-shuf"
    "uutils-sleep"
    "uutils-sort"
    "uutils-split"
    "uutils-stat"
    "uutils-stdbuf"
    "uutils-sum"
    "uutils-sync"
    "uutils-tac"
    "uutils-tail"
    "uutils-tee"
    "uutils-timeout"
    "uutils-touch"
    "uutils-tr"
    "uutils-true"
    "uutils-truncate"
    "uutils-tsort"
    "uutils-tty"
    "uutils-uname"
    "uutils-unexpand"
    "uutils-uniq"
    "uutils-unlink"
    "uutils-uptime"
    "uutils-users"
    "uutils-vdir"
    "uutils-wc"
    "uutils-who"
    "uutils-whoami"
    "uutils-yes"
  ];
  prefixLength = builtins.stringLength "uutils-";
  shellAliases = builtins.listToAttrs (map
    (name: {
      name = builtins.substring prefixLength (builtins.stringLength name) name;
      value = name;
    })
    uutils);
in
{
  options.uutils.enable = lib.mkEnableOption "uutils";
  config = lib.mkIf config.uutils.enable {
    home.shellAliases = shellAliases;
    home.packages = [ pkgs.uutils-coreutils ];
  };
}
